### ISSUE TITLE
Presentación/Video

### ISSUE THREAD

**Issue by BrunoREAR** [Organizacion-Full-Stack-ProA-Oncativo/Pagina-ProA#7]
Hacer el video de la presentación del proyecto, que no dura mas de 2 minutos y que muestre todo lo que el sitio web ofrece, características, explicación de todo el proyecto y el proceso. Explicar la idea del proyecto y las tecnologías usadas.

**Comment by csmarquez1** [comment]
Trabajo terminado por @catitasan @matiasfernandez45 @Negro06
